# Generated by Django 6.0 on 2025-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài viết', 'verbose_name_plural': 'Danh sách bài viết'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Danh sách dịch vụ'},
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Đường dẫn (Slug)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Nội dung bài viết'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blog_images/', verbose_name='Hình ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Đường dẫn (Slug)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề bài viết'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Mô tả dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Ví dụ: star, heart, soccer-ball...', max_length=50, verbose_name='Mã định danh Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/', verbose_name='Hình ảnh dịch vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Số càng nhỏ hiện càng trước', verbose_name='Thứ tự ưu tiên'),
        ),
    ]
