# Generated by Django 6.0 on 2025-12-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_name',
        ),
    ]
