# Generated by Django 6.0 on 2025-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_service_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự ưu tiên'),
        ),
    ]
