# Generated by Django 6.0 on 2025-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_summary_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('description', models.TextField(verbose_name='Mô tả ngắn')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Ảnh dịch vụ')),
                ('icon_name', models.CharField(blank=True, help_text='Tên icon (ví dụ: star, heart...)', max_length=50)),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['order'],
            },
        ),
    ]
